class Dizionario:
    def __init__(self) -> None:
        
        self.simboli = {
            r"\alpha": "α",
            r"\beta": "β",
            r"\gamma": "γ",
            r"\delta": "δ",
            r"\epsilon": "ε",
            r"\zeta": "ζ",
            r"\eta": "η",
            r"\theta": "θ",
            r"\NULL": "ι",
            r"\kappa": "κ",
            r"\lambda": "λ",
            r"\mu": "μ",
            r"\nu": "ν",
            r"\NULL": "ξ",
            r"\NULL": "ο",
            r"\pi": "π",
            r"\rho": "ρ",
            r"\NULL": "ς",
            r"\sigma": "σ",
            r"\tau": "τ",
            r"\NULL": "υ",
            r"\phi": "φ",
            r"\chi": "χ",
            r"\psi": "ψ",
            r"\omega": "ω",
            r"\Alpha": "Α",
            r"\Beta": "Β",
            r"\Gamma": "Γ",
            r"\Delta": "Δ",
            r"\Epsilon": "Ε",
            r"\Zeta": "Ζ",
            r"\Eta": "Η",
            r"\Theta": "Θ",
            r"\NULL": "Ι",
            r"\Kappa": "Κ",
            r"\Lambda": "Λ",
            r"\Mu": "Μ",
            r"\NULL": "Ν",
            r"\NULL": "Ξ",
            r"\NULL": "Ο",
            r"\Pi": "Π",
            r"\Rho": "Ρ",
            r"\Sigma": "Σ",
            r"\Tau": "Τ",
            r"\NULL": "Υ",
            r"\Phi": "Φ",
            r"\Chi": "Χ",
            r"\Psi": "Ψ",
            r"\Omega": "Ω",
            r"\\": "\\",

            r"\angs": "Å",

            r"\inf": "",
            r"\pm": "±",
            r"\sqrt": "√",
            
            r"\larrow": "",
            r"\rarrow": "",
            r"\barrow": "",
            r"\sarrow": "",

            r"\heart": "",
            r"\c_language": "",
            r"\py_language": "",
            
            r"\benzene": "",            
            r"\flask": "",
            r"\vial": "",

            r"\warning": "",
            r"\radioactive": "",
            r"\biohazard": "",
            r"\atom": "",
            r"\magnet": "",
            r"\termometer": "",
            
            r"\sun": "",
            r"\cold": "",
            r"\hot": "",
            r"\speed": "󰓅",

            r"\waveform": "󱑽",

            r"\check": "",

            r"\comunism": "󱢇",

            r"\toggle_on": "󰔡",
            r"\toggle_off": "󰨙",
        }