class Dizionario:
    def __init__(self) -> None:
        
        self.simboli = {
            "/alpha": "α",
            "/beta": "β",
            "/gamma": "γ",
            "/delta": "δ",
            "/epsilon": "ε",
            "/zeta": "ζ",
            "/eta": "η",
            "/theta": "θ",
            "/NULL": "ι",
            "/kappa": "κ",
            "/lambda": "λ",
            "/mu": "μ",
            "/nu": "ν",
            "/NULL": "ξ",
            "/NULL": "ο",
            "/pi": "π",
            "/rho": "ρ",
            "/NULL": "ς",
            "/sigma": "σ",
            "/tau": "τ",
            "/NULL": "υ",
            "/phi": "φ",
            "/chi": "χ",
            "/psi": "ψ",
            "/omega": "ω",
            "/Alpha": "Α",
            "/Beta": "Β",
            "/Gamma": "Γ",
            "/Delta": "Δ",
            "/Epsilon": "Ε",
            "/Zeta": "Ζ",
            "/Eta": "Η",
            "/Theta": "Θ",
            "/NULL": "Ι",
            "/Kappa": "Κ",
            "/Lambda": "Λ",
            "/Mu": "Μ",
            "/NULL": "Ν",
            "/NULL": "Ξ",
            "/NULL": "Ο",
            "/Pi": "Π",
            "/Rho": "Ρ",
            "/Sigma": "Σ",
            "/Tau": "Τ",
            "/NULL": "Υ",
            "/Phi": "Φ",
            "/Chi": "Χ",
            "/Psi": "Ψ",
            "/Omega": "Ω",
            "//": "/",

            "/angs": "Å",

            "/inf": "",
            "/pm": "±",
            "/sqrt": "√",
            
            "/larrow": "",
            "/rarrow": "",
            "/barrow": "",
            "/sarrow": "",

            "/heart": "",
            "/c_language": "",
            "/py_language": "",
            
            "/benzene": "",            
            "/flask": "",
            "/vial": "",

            "/warning": "",
            "/radioactive": "",
            "/biohazard": "",
            "/atom": "",
            "/magnet": "",
            "/termometer": "",
            
            "/sun": "",
            "/cold": "",
            "/hot": "",
            "/speed": "󰓅",

            "/waveform": "󱑽",

            "/check": "",

            "/comunism": "󱢇",

            "/toggle_on": "󰔡",
            "/toggle_off": "󰨙",
        }